services:
  embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:89-1.8
    container_name: text-embeddings
    ports:
      - "8080:80"
    volumes:
      - ./data:/data
    command: >
      --model-id Qwen/Qwen3-Embedding-0.6B
      --pooling mean
      --max-batch-tokens 2048
      --dtype float16
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]