services:
  text-embeddings-inference:
    image: ghcr.io/huggingface/text-embeddings-inference:89-1.8
    container_name: text-embeddings
    ports:
      - "8080:80"
    volumes:
    - ./models:/models        # <-- changed
    command: >
      --model-id /models/Qwen3-Embedding-0.6B
      --pooling last-token
      --max-batch-tokens 20000
      --max-batch-requests 512
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]