"""Add context

Revision ID: 5931cd77e93b
Revises: 7b79bfd12626
Create Date: 2025-08-30 16:17:58.752557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5931cd77e93b'
down_revision = '7b79bfd12626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('runs', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'context')
    op.drop_column('assistant', 'context')
    # ### end Alembic commands ###
